# General
run_name: "mycoplasma_small"
library_name: "Mycoplasma"
samples_tsv: "${projectDir}/shared/example/samples/barseq_samples_mycoplasma.tsv"

# Simulation
random_seed: 42

# Simulation - library
assembly_id: "GCF_000027325.1"
unique_barcodes: 10000
library_size: 500
coverage: 5
pbsim_passes: 15

# Simulation - barseq
winner_count: 5
winner_strength: 5000
count_range: "0 1000"
plusminus: 1
