run_name: "mycoplasma_small"
assembly_id: "GCF_000027325.1"
library_name: "Mgenitalium"
unique_barcodes: 10000
library_size: 500
coverage: 5
pbsim_passes: 15
random_seed: 42
samples_tsv: "${projectDir}/../shared/example/samples/barseq_samples_mycoplasma.tsv"
bobaseq_json: "${projectDir}/../shared/defaults/bobaseq_config.json"
oligo_path: "${projectDir}/../shared/defaults/oligos.fasta"
