# General
outdir: "results/pelagibacter_small"
library_name: "Pelagibacter"
samples_tsv: "${projectDir}/../shared/example/samples/barseq_samples_pelagibacter.tsv"

# Simulation
random_seed: 42

# Simulation - library
assembly_id: "GCF_000012345.1"
unique_barcodes: 20000
library_size: 1000
coverage: 5
pbsim_passes: 15

# Simulation - barseq
winner_count: 5
winner_strength: 5000
count_range: "0 1000"
plusminus: 1
