run_name: "pelagibacter_small"
assembly_id: "GCF_000012345.1"
library_name: "Pelagibacter"
unique_barcodes: 20000
library_size: 1000
coverage: 5
pbsim_passes: 15
random_seed: 42
samples_tsv: "${projectDir}/../shared/example/samples/barseq_samples_pelagibacter.tsv"
bobaseq_json: "${projectDir}/../shared/defaults/bobaseq_config.json"
oligo_path: "${projectDir}/../shared/defaults/oligos.fasta"
